added more config options

diff --git a/xmr-mine b/xmr-mine
--- a/xmr-mine
+++ b/xmr-mine
@@ -28,47 +28,82 @@ REQUIREMENTS
         timesyncd.service before launching xmr-stak.
 
 OPTIONS
-    -B, --background
+    --background, -B
         Set verbose_level=0, launch in daemon mode, and
         fork to background.
 
-    -C, --config
+    --config, -C
         Use XMR_CONFIG file as config.txt.
 
     --cpu
         Use XMR_CPU file as cpu.txt.
 
-    -D, --dryrun
+    --dryrun, D
         Run script and generate config.txt without launching xmr-stak
 
-    -G, --gen-config, --generate-config
+    --gen-config, -G
         Use xmr-stak to generate a new config in the DIR_MINE directory.
         Newly generated config files must be copied manually to XMR_CONFIG
         if future use is desired.
 
-    -H, --hash
-        Print hash rate.
-
     --help
         Print help.
 
-    -I, --incognito
-        Launch xmr-stak in daemon mode piping all output to /dev/null.
-
-    -K, --kill
+    --kill, -K
         Kill any instances of xmr-stak.
 
-    -N, --nvidia
+    --nvidia, -N
         Use XMR_NVIDIA file as nvidia.txt.
 
-    -R, --random-pool, --random-weight
+    --pool, -p <ADDRESS:PORT>
+        Specify default pool address and port number.  Pool is added
+        to the list of pools and given the highest weight.
+
+    --password, --pass <POOL PASSWORD>
+        Password used to login to default pool.  HOSTNAME is used if no
+        password is specified.
+
+    --quiet, -Q
+        Launch xmr-stak in daemon mode.  Pipe all output to /dev/null.
+
+    --random-pool, -R
         Randomize pool weights.
 
-    -S, --status
+    --show-hash, -H
+        Print hash rate.
+
+    --show-status, -S
         Print current pool status and hash rate.
 
-    -W, --wallet
+    --show-wallet, -W
         Print XMR wallet address.
+
+    --wallet, -w <XMR ADDRESS>
+        Specify xmr wallet to mine to.
+
+ENVIRONMENT VARIABLES
+    The default behavior of xmr-mine can may be affected by
+    setting optional environment variables.
+
+    XMR_WALLET
+        Default wallet address.
+
+    XMR_POOL
+        Default xmr mining pool address and port number.  This is added
+        to the list of pools addresses and given the highest weight.
+
+    XMR_POOL_PASSWORD
+        Pool password used for default pool.  HOSTNAME is used if no
+        password is set.  Some pools arc capable a monitoring
+        individual miners identified by the pool password.
+
+    XMR_CONFIG_DIRECTORY
+        Directory containing any xmr-stak configuration files.  ~/.xmr-mine
+        is used if left unset.
+
+CONFIGURATION FILES
+
+
 
 CONFIGURATION
     Every xmr-stak config.txt variable is set in the XMR-STAK SETTINGS
@@ -76,8 +111,8 @@ CONFIGURATION
     run unless a config file is specified.  (Right now cpu.txt and
     nvidia.txt can be either specified or generated by xmr-stak.)
 
-    A valid machine lookup name must be specified by MINER_NAME in order
-    to correctly display miner stats.
+    A valid machine hostname and domain must be specified by
+    MINER_NAME in order to correctly display miner stats.
 
 SEE ALSO:
     https://github.com/arcmags/xmr-mine
@@ -87,8 +122,11 @@ EODOC
 
 
 ##=======================  XMR-STAK SETTINGS  ========================##
-# wallet:
+# default wallet:
 wallet_address="$XMR_WALLET"
+# default pool:
+pool_address="$XMR_POOL"
+pool_password="${XMR_POOL_PASSWORD:-$HOSTNAME}"
 # pools:
 pool_addresses=(
     'pool.supportxmr.com:3333'
@@ -130,9 +168,10 @@ prefer_ipv4='true'
 
 ##===========================  VARIABLES  ============================##
 # default xmr-stak config files:
-XMR_CONFIG="$HOME/.xmr-mine/config.txt"
-XMR_CPU="$HOME/.xmr-mine/cpu.txt"
-XMR_NVIDIA="$HOME/.xmr-mine/nvidia.txt"
+DIR_CONFIG="$HOME/.xmr-mine"
+XMR_CONFIG="$DIR_CONFIG/config.txt"
+XMR_CPU="$DIR_CONFIG/cpu.txt"
+XMR_NVIDIA="$DIR_CONFIG/nvidia.txt"
 # machine name (for printing stats):
 MINER_NAME="$HOSTNAME.localdomain"
 # script variables:
@@ -149,7 +188,7 @@ FLAG_INCOGNITO='false'
 FLAG_CONFIG_NEW='false'
 FLAG_KILL='false'
 FLAG_NVIDIA_FILE='false'
-FLAG_RANDOM_WEIGHTS='false'
+FLAG_RANDOM_POOL='false'
 FLAG_STATUS='false'
 FLAG_WALLET='false'
 
@@ -171,8 +210,30 @@ ntp_check() {
         grep 'timesyncd.service active: yes' >/dev/null`
 }
 
-# Check miner state.
-mine_check() {
+# Execute specified action from FLAG.
+mine_action()
+    # print help:
+    if [ "$FLAG_HELP" = 'true' ]; then
+        print_help
+        exit 0
+    # kill any xmr-stak instance:
+    elif [ "$FLAG_KILL" = 'true' ]; then
+        mine_kill
+        exit 0
+    # print pool status and hash rate:
+    elif [ "$FLAG_HASH" = 'true' ] || [ "$FLAG_STATUS" = 'true' ]; then
+        print_mine_status
+        exit 0
+    # print wallet address:
+    elif [ "$FLAG_WALLET" = 'true' ]; then
+        print_wallet
+        exit 0
+    fi
+    return 0
+}
+
+# Precheck system before launching xmr-stak.
+mine_precheck() {
     # FAIL: no AES support:
     if !(cat /proc/cpuinfo | grep -P 'flags\s*:.* aes( |$)' >/dev/null); then
         printf ":! CPU does not support AES\n"
@@ -311,14 +372,21 @@ nvidia_file() {
 config_build() {
     local XMR_CONFIG_TEXT=''
     # generate random pool weights:
-    if [ "$FLAG_RANDOM_WEIGHTS" = 'true' ]; then
+    if [ "$FLAG_RANDOM_POOL" = 'true' ]; then
         pool_weights=( `shuf -i 1-${#pool_addresses[@]} \
             -n ${#pool_addresses[@]}` )
     fi
-    # add pool list:
+    # add default pool:
+    if [ -n "$pool_address" ]; then
+        pool_addresses+=( "$pool_address" )
+        pool_weights+=( ${#pool_addresses[@]} )
+        pool_passwords+=( "$pool_password" }
+    fi
+    # begin pool list:
     XMR_CONFIG_TEXT="\"pool_list\" :\n"
     XMR_CONFIG_TEXT+="[\n"
     i=0
+    # add pools:
     for POOL in ${pool_addresses[@]}; do
         XMR_CONFIG_TEXT+="  {\n"
         XMR_CONFIG_TEXT+="    \"pool_address\" : \"$POOL\",\n"
@@ -357,48 +425,35 @@ config_build() {
 
 ##=============================  SCRIPT  =============================##
 # parse args:
-for arg in "$@"; do case $arg in
-    -B|--background)  shift;  FLAG_DAEMON='true'                     ;;
-    -C|--config)      shift;  FLAG_CONFIG_FILE='true'             ;;
-    --cpu)            shift;  FLAG_CPU_FILE='true'             ;;
-    -D|--dryrun)      shift;  FLAG_DRYRUN='true'                 ;;
-    -G|--gen-config|--generate-config)  shift;  FLAG_CONFIG_NEW='true'  ;;
-    -H|--hash)        shift;  FLAG_HASH='true'                       ;;
-    --help)           shift;  FLAG_HELP='true'                       ;;
-    -I|--incognito)   shift;  FLAG_INCOGNITO='true'; FLAG_DAEMON='true'  ;;
-    -K|--kill)        shift;  FLAG_KILL='true'                       ;;
-    -N|--nvidia)      shift;  FLAG_NVIDIA_FILE='true'  ;;
-    -R|--random-pool)  shift;  FLAG_RANDOM_WEIGHTS='true'    ;;
-    -S|--status)      shift;  FLAG_STATUS='true'                     ;;
-    -W|--wallet)      shift;  FLAG_WALLET='true'                     ;;
-esac; done
+while [ -n "$1" ]; do case $1 in
+#for arg in "$@"; do case $arg in
+    --background|-B)   FLAG_DAEMON='true'                    ;;
+    --config|-C)       FLAG_CONFIG_FILE='true'               ;;
+    --cpu)             FLAG_CPU_FILE='true'                  ;;
+    --dryrun|-D)       FLAG_DRYRUN='true'                    ;;
+    --gen-config|-G)   FLAG_CONFIG_NEW='true'                ;;
+    --hash|-H)         FLAG_HASH='true'                      ;;
+    --help)            FLAG_HELP='true'                      ;;
+    --kill|-K)         FLAG_KILL='true'                      ;;
+    --nvidia|-N)       FLAG_NVIDIA_FILE='true'               ;;
+    --pool|-p)         shift; pool_address="$1"              ;;
+    --password|--pass) shift; pool_password="$1"             ;;
+    --quiet|-Q|-I)     FLAG_QUIET='true'; FLAG_DAEMON='true' ;;
+    --random-pool|-R)  FLAG_RANDOM_POOL='true'               ;;
+    --show-hash|-H)    FLAG_HASH='true'                      ;;
+    --show-status|-S)  FLAG_STATUS='true'                    ;;
+    --show-wallet|-W)  FLAG_WALLET='true'                    ;;
+    --wallet|-w)       shift; wallet_address="$1"            ;;
+    # FAIL: unrecognized option:
+    *)  printf ":! unrecognized option: $1\n"
+        exit 5 ;;
+esac; shift; done
 
-# print help:
-if [ "$FLAG_HELP" = 'true' ]; then
-    print_help
-    exit 0
-fi
+# execute command line specified action:
+mine_action
 
-# kill any xmr-stak instance:
-if [ "$FLAG_KILL" = 'true' ]; then
-    mine_kill
-    exit 0
-fi
-
-# print pool status and hash rate:
-if [ "$FLAG_HASH" = 'true' ] || [ "$FLAG_STATUS" = 'true' ]; then
-    print_mine_status
-    exit 0
-fi
-
-# print wallet address:
-if [ "$FLAG_WALLET" = 'true' ]; then
-    print_wallet
-    exit 0
-fi
-
-# check miner state:
-mine_check
+# precheck system before firing up miner:
+mine_precheck
 
 # switch to mining directory:
 mkdir -p "$DIR_MINE"
